version: 0.2

phases:
  build:
    commands:
      - echo "Hello!!!"
      - java -version
      - javac src/org/twenty20twenty/Twenty20Twenty.java
      - zip -r build.jar *
artifacts:
  files:
    - build.jar
